name: Publish package to the ForgeRock artifactory
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up forgerock maven repository
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: '11'
          architecture: x64
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: FR_ARTIFACTORY_USER
          server-token: FR_ARTIFACTORY_CENTRAL_TOKEN

      - name: Release package
        run:  mvn -B deploy
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          FR_ARTIFACTORY_CENTRAL_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}